package com.example.demo.Dtos;


import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for creating or updating a Keynote speaker.
 * The 'id' is excluded as it should be generated by the server.
 */
@Data
@NoArgsConstructor
public class KeynoteRequestDTO {

    @NotBlank(message = "Last name cannot be blank")
    private String nom;

    @NotBlank(message = "First name cannot be blank")
    private String prenom;

    @NotBlank(message = "Email cannot be blank")
    private String email;

    @NotBlank(message = "Function/title cannot be blank")
    private String fonction;
}