package com.example.demo;

import com.example.demo.entities.Keynote;
import com.example.demo.repository.KeynoteRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.List;

@SpringBootApplication
public class KeyConfApplication {

	public static void main(String[] args) {
		SpringApplication.run(KeyConfApplication.class, args);
	}

    @Bean
    CommandLineRunner initKeynoteDatabase(KeynoteRepository keynoteRepository) {

        return args -> {
            // Create 3 sample Keynote speakers
            Keynote keynote1 = Keynote.builder()
                    .nom("El Amrani")
                    .prenom("Fatima")
                    .email("fatima.elamrani@example.com")
                    .fonction("Senior Cloud Architect")
                    .build();

            Keynote keynote2 = Keynote.builder()
                    .nom("Chen")
                    .prenom("Wei")
                    .email("w.chen@example.com")
                    .fonction("AI/ML Research Lead")
                    .build();

            Keynote keynote3 = Keynote.builder()
                    .nom("Smith")
                    .prenom("David")
                    .email("david.smith@example.com")
                    .fonction("Principal DevOps Engineer")
                    .build();

            // Save them all to the database
            // The IDs will be automatically generated by JPA
            keynoteRepository.saveAll(List.of(keynote1, keynote2, keynote3));
        };
    }

}
